# Generated by Django 3.1 on 2020-09-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
