# Generated by Django 3.1 on 2020-09-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unit',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
