# Generated by Django 3.1 on 2020-10-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_post_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
        migrations.AlterField(
            model_name='post',
            name='total_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='unit',
            field=models.CharField(choices=[('kg', 'kilogram'), ('gm', 'gram'), ('nm', 'Number')], default='nm', max_length=2),
        ),
    ]
